wordpress:
 image: wordpress
 volumes:
   - .:/var/www/html/wp-content/plugins/GuitarPracticeRoutineTracker
 links:
  - mysql
 environment:
  - WORDPRESS_DB_PASSWORD=testonlypassword
 ports:
  - "8080:80"
mysql:
 image: mysql:5.7
 environment:
  - MYSQL_ROOT_PASSWORD=testonlypassword
  - MYSQL_DATABASE=my-wpdb
 